// Generated by perry-styling — do not edit manually
// Re-generate: perry-styling generate --tokens tokens.json --out examples/theme.ts

export interface PerryColor { r: number; g: number; b: number; a: number }

export interface PerryColors {
  primary: PerryColor;
  surface: PerryColor;
  card:    PerryColor;
  text:    PerryColor;
  muted:   PerryColor;
  accent:  PerryColor;
  danger:  PerryColor;
}

export interface PerryTheme {
  light:       PerryColors;
  dark:        PerryColors;
  spacing:     { sm: number; md: number; lg: number; xl: number };
  radius:      { sm: number; md: number; lg: number; xl: number };
  fontSize:    { sm: number; base: number; lg: number; xl: number; hero: number };
  borderWidth: { none: number; thin: number; sm: number; md: number; lg: number };
}

export const theme: PerryTheme = {
  light: {
    primary:  { r: 0.231, g: 0.510, b: 0.965, a: 1.000 },  // #3B82F6
    surface:  { r: 1.000, g: 1.000, b: 1.000, a: 1.000 },  // #FFFFFF
    card:     { r: 0.953, g: 0.957, b: 0.965, a: 1.000 },  // #F3F4F6
    text:     { r: 0.067, g: 0.094, b: 0.153, a: 1.000 },  // #111827
    muted:    { r: 0.420, g: 0.447, b: 0.502, a: 1.000 },  // #6B7280
    accent:   { r: 0.063, g: 0.725, b: 0.506, a: 1.000 },  // #10B981
    danger:   { r: 0.937, g: 0.267, b: 0.267, a: 1.000 },  // #EF4444
  },
  dark: {
    primary:  { r: 0.376, g: 0.647, b: 0.980, a: 1.000 },  // #60A5FA
    surface:  { r: 0.110, g: 0.110, b: 0.118, a: 1.000 },  // #1C1C1E
    card:     { r: 0.173, g: 0.173, b: 0.180, a: 1.000 },  // #2C2C2E
    text:     { r: 0.976, g: 0.980, b: 0.984, a: 1.000 },  // #F9FAFB
    muted:    { r: 0.612, g: 0.639, b: 0.686, a: 1.000 },  // #9CA3AF
    accent:   { r: 0.204, g: 0.827, b: 0.600, a: 1.000 },  // #34D399
    danger:   { r: 0.973, g: 0.443, b: 0.443, a: 1.000 },  // #F87171
  },
  spacing:     { sm: 8, md: 16, lg: 24, xl: 32 },
  radius:      { sm: 4, md: 8, lg: 12, xl: 24 },
  fontSize:    { sm: 12, base: 16, lg: 20, xl: 28, hero: 36 },
  borderWidth: { none: 0, thin: 0.5, sm: 1, md: 2, lg: 4 },
};
