//! JNI bridge generation for native LLVM-compiled widget providers on Wear OS
//!
//! Generates Kotlin code that loads the native library and calls the provider function.
//! Same pattern as phone Glance widgets — Wear OS is Android.

use perry_hir::ir::*;
use std::fmt::Write;

/// Emit the JNI bridge Kotlin class for the native provider (Wear OS tile)
pub fn emit_bridge(widget: &WidgetDecl, name: &str, package: &str) -> String {
    let mut out = String::new();

    writeln!(out, "// Auto-generated by Perry compiler — do not edit").unwrap();
    writeln!(out, "package {}", package).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import android.content.Context").unwrap();
    writeln!(out, "import org.json.JSONObject").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "object {}TileBridge {{", name).unwrap();
    writeln!(out, "    init {{").unwrap();
    writeln!(out, "        System.loadLibrary(\"widget_provider\")").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    if let Some(ref func_name) = widget.provider_func_name {
        writeln!(out, "    @JvmStatic").unwrap();
        writeln!(out, "    private external fun {}(configJson: String): String", func_name).unwrap();
        writeln!(out).unwrap();
        writeln!(out, "    @JvmStatic").unwrap();
        writeln!(out, "    private external fun perry_runtime_widget_init()").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "    private var appContext: Context? = null").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    @JvmStatic").unwrap();
    writeln!(out, "    fun sharedStorageGet(key: String): String {{").unwrap();
    writeln!(out, "        val prefs = appContext?.getSharedPreferences(\"perry_shared\", Context.MODE_PRIVATE)").unwrap();
    writeln!(out, "        return prefs?.getString(key, \"\") ?: \"\"").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    fun fetchEntry(context: Context): {}Entry {{", name).unwrap();
    writeln!(out, "        appContext = context.applicationContext").unwrap();

    if let Some(ref func_name) = widget.provider_func_name {
        writeln!(out, "        perry_runtime_widget_init()").unwrap();
        writeln!(out, "        val resultJson = {}(\"{{}}\")", func_name).unwrap();
        writeln!(out, "        return try {{").unwrap();
        writeln!(out, "            val result = JSONObject(resultJson)").unwrap();
        writeln!(out, "            val entries = result.getJSONArray(\"entries\")").unwrap();
        writeln!(out, "            if (entries.length() > 0) {{").unwrap();
        writeln!(out, "                val e = entries.getJSONObject(0)").unwrap();
        write!(out, "                {}Entry(", name).unwrap();
        let field_strs: Vec<String> = widget.entry_fields.iter()
            .map(|(fname, ftype)| {
                match ftype {
                    WidgetFieldType::String => format!("{} = e.optString(\"{}\", \"\")", fname, fname),
                    WidgetFieldType::Number => format!("{} = e.optDouble(\"{}\", 0.0)", fname, fname),
                    WidgetFieldType::Boolean => format!("{} = e.optBoolean(\"{}\", false)", fname, fname),
                    _ => format!("{} = e.optString(\"{}\", \"\")", fname, fname),
                }
            })
            .collect();
        write!(out, "{}", field_strs.join(", ")).unwrap();
        writeln!(out, ")").unwrap();
        writeln!(out, "            }} else {{ defaultEntry() }}").unwrap();
        writeln!(out, "        }} catch (e: Exception) {{ defaultEntry() }}").unwrap();
    } else {
        writeln!(out, "        return defaultEntry()").unwrap();
    }

    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    write!(out, "    private fun defaultEntry() = {}Entry(", name).unwrap();
    let defaults: Vec<String> = widget.entry_fields.iter()
        .map(|(_, ftype)| kotlin_default_value(ftype))
        .collect();
    write!(out, "{}", defaults.join(", ")).unwrap();
    writeln!(out, ")").unwrap();

    writeln!(out, "}}").unwrap();
    out
}

fn kotlin_default_value(field_type: &WidgetFieldType) -> String {
    match field_type {
        WidgetFieldType::String => "\"\"".to_string(),
        WidgetFieldType::Number => "0.0".to_string(),
        WidgetFieldType::Boolean => "false".to_string(),
        WidgetFieldType::Array(_) => "emptyList()".to_string(),
        WidgetFieldType::Optional(_) => "null".to_string(),
        WidgetFieldType::Object(_) => "emptyMap()".to_string(),
    }
}
